pkg_url="http://download.enlightenment.org/rel/apps/terminology/terminology-1.1.1.tar.xz"
pkg_ext="tar.xz"
pkg_rel=""
src_build="c"
src_prefix="/usr/local"
src_cflags="-O2 -ffast-math -march=native -g -ggdb3"
src_cxxflags=""
src_configure=""
