pkg_url="https://git.enlightenment.org/apps/express.git"
pkg_ext="git"
pkg_rel=""
src_build="c"
src_prefix="/usr/local"
src_cflags="-O2 -ffast-math -march=native -g -ggdb3"
src_cxxflags=""
src_configure=""
