pkg_url="http://download.enlightenment.org/rel/apps/enlightenment/enlightenment-0.21.3.tar.gz"
pkg_ext="tar.gz"
pkg_rel=""
src_build="c"
src_prefix="/usr/local"
src_cflags="-O2 -ffast-math -march=native -g -ggdb3"
src_cxxflags=""
src_configure=""
