pkg_url="https://github.com/cython/cython/archive/0.17.3.tar.gz"
pkg_ext="tar.gz"
pkg_rel=""
src_build="c"
src_prefix="/usr/local"
src_cflags="-O2 -ffast-math -march=native -g -ggdb3"
src_cxxflags=""
src_configure=""
