pkg_url="https://git.enlightenment.org/tools/erigo.git"
pkg_ext="git"
pkg_rel="v1.0.0_1.14-beta3"
src_build="c"
src_prefix="/usr/local"
src_cflags="-O2 -ffast-math -march=native -g -ggdb3"
src_cxxflags=""
src_configure=""
