pkg_url="https://github.com/ajwillia-ms/edi/releases/download/v0.4.0/edi-0.4.0.tar.bz2"
pkg_ext="tar.bz2"
pkg_rel=""
src_build="c"
src_prefix="/usr/local"
src_cflags="-O2 -ffast-math -march=native -g -ggdb3"
src_cxxflags=""
src_configure=""
